### ISSUE TITLE
Exception: ReferenceError: encode is not defined

### ISSUE THREAD

**Issue by hsjeevan** [Twingate-Labs/tg-cli#12]
Getting the following error while deploying to OCI.

Reference - [How to remotely access Oracle Cloud OCI without a VPN](https://www.youtube.com/watch?v=Bjs9xYJ6o9c)
```
[INFO]    Creating VM, please wait.
[ERROR]   Exception: ReferenceError: encode is not defined
    at OracleVmDeployer.createVm (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:78998:24)
    at OracleVmDeployer.deploy (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:79034:37)
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async Command.fn (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:79065:28)
    at async Command.execute (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:2536:13)
    at async main1 (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:80721:12)
    at async file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:80724:5
```

**Comment by emrul** [comment]
Hi @hsjeevan, thank you for reporting this. We will investigate it right away and update.
