### ISSUE TITLE
tg oci deploy error

### ISSUE THREAD

**Issue by giovannicandido** [Twingate-Labs/tg-cli#3]
Hi I run the command `tg deploy oci vm` and I get the error below:

```
tg deploy oci vm
[INFO]    Using Twingate account: 'xxxx'
[ERROR]   Exception: NotFound: No such file or directory (os error 2)
    at opRun (deno:runtime/js/40_process.js:29:16)
    at Object.run (deno:runtime/js/40_process.js:112:17)
    at execCmd (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:10304:20)
    at OracleVmDeployer.checkAvailable (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:76069:34)
    at OracleVmDeployer.deploy (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:80891:20)
    at async OracleVmDeployer.deploy (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:81124:9)
    at async Command.fn (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:81172:28)
    at async Command.execute (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:2493:13)
    at async Command.parse (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:2313:20)
    at async main2 (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:82074:12)
````

**Comment by emrul** [comment]
Hi @giovannicandido - thanks for reporting this, can you let me know what operating system / platform you're running the CLI on?

**Comment by giovannicandido** [comment]
Hi, I'm using Arch Linux  on WSL Windows environment

**Comment by emrul** [comment]
Thanks @giovannicandido - we were using the POSIX `[command](https://pubs.opengroup.org/onlinepubs/007904975/utilities/command.html)`  to detect presence of CLI commands but it seems not as widely supported as we'd hoped. Have refactored this and cut a new release.  Would you be able to try the latest release and let me know your feedback?

**Comment by giovannicandido** [comment]
The latest release is working. Thanks

**Comment by emrul** [comment]
Fantastic, thank you for reporting this!
