### ISSUE TITLE
Since v0.0.54 "TypeError: Deno.setRaw is not a function” occurs.

### ISSUE THREAD

**Issue by htnosm** [Twingate-Labs/tg-cli#6]
It seems that binaries no longer work from v0.0.54.
It output "TypeError: Deno.setRaw is not a function”.

## Expected Behavior
[v0.0.53](https://github.com/Twingate-Labs/tg-cli/releases/download/v0.0.53/cli_linux_x86_64.zip) zip.
```
$ tg --version
tg CLI Version: 0.0.53 | TwingateApiClient Version: 0.1.0
$ tg connector list
 ? Enter Twingate account: ›
 ❯ For example, 'acme' for 'acme.twingate.com'
```

## Current Behavior
[v0.0.54](https://github.com/Twingate-Labs/tg-cli/releases/download/v0.0.54/cli_linux_x86_64.zip) zip.
Each command cannot be executed.
```
$ tg --version
tg CLI Version: 0.0.54 | TwingateApiClient Version: 0.1.0
$ tg connector list
 ? Enter Twingate account: › [ERROR]   Exception: TypeError: Deno.setRaw is not a function
    at Input.#readChar (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:6179:18)
    at Input.#readKey (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:6172:42)
    at Input.read (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:6121:47)
    at Input.#execute (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:6072:25)
    at async Input.prompt (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:6058:20)
    at async PromptList.runPrompt (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:7380:45)
    at async file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:7312:17
    at async PromptList.runBeforeHook (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:7368:9)
    at async PromptList.next (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:7310:13)
    at async PromptList.run (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:7305:9)
$
```

**Comment by htnosm** [comment]
FYI, 
When I checked deno-cliffy with reference to past issues, the following issues were posted.
[TypeError: Deno\.setRaw is not a function · Issue \#458 · c4spar/deno\-cliffy](https://github.com/c4spar/deno-cliffy/issues/458)
Also, it seems that the version used has changed from v0.0.54. https://github.com/Twingate-Labs/tg-cli/commit/6f65b16a2a8aa3fa915d03af63139fa009858c6d

**Comment by chenbishop** [comment]
@htnosm thank you very much for your ticket. The issue has been fixed with version v0.0.56.  Closing the issue, please create a new ticket if you experience further issues.
